openapi: 3.0.0
info:
  version: 1.0
  title: easyform
  description: API documentation based on restful api in easyform project
  license:
    name: HRJW
tags:
  - name: auth
    description: Authentication related API
paths:
  /auth/token:
    post:
      tags:
        - auth
      summary: Token issuance through authentication
      description: Token issuance through authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:        
                  type: string
                  enum: [GOOGLE, KAKAO, NAVER]
                token:
                  type: string
              required:
                - type
                - token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/responses'    
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/responses'

components:
 responses:
    type: object
    properties:
      message:
        type: string
        description: response message
      data:
        type: object 
        description: response data
    
