openapi: 3.0.0
info:
  version: "1.0"
  title: easyform
  description: API documentation based on restful api in easyform project
  license:
    name: HRJW
tags:
  - name: auth
    description: Authentication related API
paths:
  /auth/token:
    $ref: './auth.token.yaml'
  /survey:
    $ref: './survey.yaml'

components:
  responses:
    SUCCESS:
      type: string 
      example: success
    MISSING_REQUIRED_QUERY_PRAMETER:
      type: string 
      example: missing required query parameter
    PRAMETER_VALUE_NOT_SATISFIED:
      type: string 
      example: parameter value not satisfied
    SNS_AUTH_FAILED:
      type: string 
      example: SNS_AUTH_FAILED
    INVALID_TOKEN:
      type: string 
      example: invalid token
    REISSUANCE_ACCESS_TOKEN:
      type: string 
      example: Reissuance of access token
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT   