openapi: 3.0.0
info:
  version: 1.0
  title: easyform
  description: API documentation based on restful api in easyform project
  license:
    name: HRJW
tags:
  - name: auth
    description: Authentication related API
paths:
  /auth/token:
    post:
      tags:
        - auth
      summary: Token issuance through authentication
      description: Token issuance through authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:        
                  type: string
                  enum: [google, kakao, naver]
                token:
                  type: string
              required:
                - type
                - token
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/responses/200'    
        '400':
          description: Missing the type or token field or sending an incorrect type
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'

components:
 responses:
    200:
      type: object
      properties:
        code:
          type: integer
          description: The user ID.
          example: 0
    400:
      type: object
      properties:
        code:
          type: integer
          description: 1 or 2
          example: 1
